#include "filter.h"

float DigFil(float invar)
/******************************************************************************/
/* Filter Solutions Version 2015                 Nuhertz Technologies, L.L.C. */
/*                                                            www.nuhertz.com */
/*                                                            +1 602-279-2448 */
/* 2nd Order Low Pass Bessel                                                  */
/* Matched Z Transformation                                                   */
/* Sample Frequency = 10.00 KHz                                               */
/* Standard Form                                                              */
/* Arithmetic Precision = 4 Digits                                            */
/*                                                                            */
/* Pass Band Frequency = 100.0 Hz                                             */
/* Pass Band Attenuation = 3.01 dB                                            */
/*                                                                            */
/******************************************************************************/
/*                                                                            */
/* Input Variable Definitions:                                                */
/* Inputs:                                                                    */
/*   invar    float       The input to the filter                             */
/*                                                                            */
/* Option Selections:                                                         */
/* C++;          Not Initializable;        Internal States;   Not Optimized;  */
/*                                                                            */
/* There is no requirement to ever initialize the filter.                     */
/* The default initialization is zero when the filter is first called         */
/*                                                                            */
/******************************************************************************/
/*                                                                            */
/* This software is automatically generated by Filter Solutions               */
/* no restrictions from Nuhertz Technologies, L.L.C. regarding the use and    */
/* distributions of this software.                                            */
/*                                                                            */
/******************************************************************************/

{
	static float states[2] = { 0.0,0.0 };
	const static float znum[3] = {
		0.0,
		0.0,
		5.963e-03
	};
	const static float zden[2] = {
		.8707,
		-1.865
	};
	float sumden(0.0), sumnum(0.0);
	for (int i = 0; i<2; i++) {
		sumden += states[i] * zden[i];
		sumnum += states[i] * znum[i];
		if (i<1) states[i] = states[i + 1];
	}
	states[1] = invar - sumden;
	sumnum += states[1] * znum[2];
	return sumnum;
}
